/* eslint-disable */
// tslint:disable
/**
 * Objects API
 * API for managing objects
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

export namespace Api {
	export interface ApiKey {
		/**
		 * @description <p>Generated API key</p>
		 * @type {string}
		 * @memberof ApiKey
		 */
		apiKey?: string;
	}

	export interface AuthCredentials {
		/**
		 * @description <p>User&#39;s username</p>
		 * @type {string}
		 * @memberof AuthCredentials
		 */
		username: string;
		/**
		 * @description <p>User&#39;s password</p>
		 * @type {string}
		 * @memberof AuthCredentials
		 */
		password: string;
	}

	export interface Error {
		/**
		 * @description <p>Error message</p>
		 * @type {string}
		 * @memberof Error
		 */
		error?: string;
	}

	export interface Marker {
		/**
		 * @type {number}
		 * @memberof Marker
		 * minimum: 0
		 */
		markerId?: number;
		/**
		 * @type {number}
		 * @memberof Marker
		 * minimum: 0
		 */
		subnet: number;
		/**
		 * @type {number}
		 * @memberof Marker
		 * minimum: 0
		 */
		node: number;
		installPosition?: Api.Marker.InstallPosition;
		activated?: boolean;
		activationTime?: Date;
	}
	
	/**
	 * @export
	 * @namespace Marker
	 */
	export namespace Marker {
		export interface InstallPosition {
			/**
			 * @type {number}
			 * @memberof InstallPosition
			 */
			x?: number;
			/**
			 * @type {number}
			 * @memberof InstallPosition
			 */
			y?: number;
			/**
			 * @type {number}
			 * @memberof InstallPosition
			 */
			z?: number;
		}
	
	}

	export interface Reading {
		/**
		 * @type {number}
		 * @memberof Reading
		 * minimum: 0
		 */
		readingId?: number;
		timestamp?: Date;
		/**
		 * @type {number}
		 * @memberof Reading
		 */
		temperature?: number;
		/**
		 * @type {number}
		 * @memberof Reading
		 */
		porePressure?: number;
	}

	export interface Reading2 {
		/**
		 * @type {number}
		 * @memberof Reading2
		 * minimum: 0
		 */
		readingId?: number;
		timestamp: Date;
		/**
		 * @type {number}
		 * @memberof Reading2
		 */
		temperature?: number;
		/**
		 * @type {number}
		 * @memberof Reading2
		 */
		porePressure?: number;
	}

}
