/* eslint-disable */
// tslint:disable
/**
 * Objects API
 * API for managing objects
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import * as auth from './api/auth/types'
import * as marker from './api/marker/types'
import * as markers from './api/markers/types'

export interface ApiImplementation {
	auth: auth.AuthApi
	marker: marker.MarkerApi
	markers: markers.MarkersApi
}
