/* eslint-disable */
// tslint:disable
/**
 * Objects API
 * API for managing objects
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface MarkerApi {
	getMarker: (__user: any) => Promise<GetMarkerResponse>
	postMarker: (request: Api.Marker, __user: any) => Promise<PostMarkerResponse>
}

export type GetMarkerResponse = GetMarker200Response

export interface GetMarker200Response {
	status: 200
	body: Api.Marker[]
	headers?: never
}

export type PostMarkerResponse = PostMarker201Response

export interface PostMarker201Response {
	status: 201
	body: Api.Marker
	headers?: never
}

